# sshd_config defaults on QNX
UsePAM yes
KbdInteractiveAuthentication no
PasswordAuthentication yes
PermitUserEnvironment yes
PermitRootLogin no
PrintMotd no

Protocol 2
Ciphers aes128-ctr,aes192-ctr,aes256-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256
SshdSessionPath /usr/lib/ssh/sshd-session


