
# Simulator camera i.e. color bars
begin SENSOR_UNIT_1
    type = simulator_camera
    name = front
    position = 0, 0, 0
    direction = 0, 0, 0
    default_video_resolution = 1280, 720
    default_video_format = bgr8888
    num_user_buffers = 4
end SENSOR_UNIT_1

# Video playback of simulator camera i.e. color bars
begin SENSOR_UNIT_2
    type = file_camera
    address = /data/share/sensor/simulator_camera.mov
end SENSOR_UNIT_2
